
(window.callback73346=window.callback73346||Bootstrapper.new_fArray()).add(function(){Bootstrapper.setCurrentRuleId(73346);Bootstrapper.bindDOMParsed(function(){try{Bootstrapper.setCurrentRuleId(82082);if($(".moreHelp").length>0){var ti,scnct;var REGEX_ACCT=/account/i;scnct="techsupport";if(REGEX_ACCT.test(window.location.pathname))
{scnct="account";$(".moreHelp").attr({"ms.scn":"account & billing","ms.scvalue":"account & billing","ms.scnum":"60.1"});}
$(".moreHelp").attr({"ms.cmptyp":"link","ms.cmpnm":"contactus","ms.scnct":scnct,"ms.contentproperties":"assisted"});var more_a=$(".moreHelp a");ti=more_a.attr("bi:title")||"ask answer desk";more_a.attr({"ms.interactiontype":"1","ms.title":ti,"ms.ea_action":"request","ms.ea_name":"answer desk","ms.ea_offer":"support"});}}catch(e){Bootstrapper.reportException(e);}});});(window.callback73346=window.callback73346||Bootstrapper.new_fArray()).add(function(){Bootstrapper.setCurrentRuleId(73346);Bootstrapper.bindDOMParsed(function(){try{Bootstrapper.setCurrentRuleId(73720);function setMsTitle(ele,cmpnm,cmptyp,interactionType){var biTitle=$(ele).attr("bi:title");var ti=(biTitle&&biTitle.indexOf("javascript")==-1)?biTitle:$(ele).text().trim();ti=ti.toLowerCase();$(ele).attr({"ms.cmpnm":cmpnm,"ms.cmptyp":cmptyp,'ms.title':ti,'ms.interactiontype':interactionType});}
(function(){var ti;$(".main-content").removeAttr("ms.cmpgrp");$("#topRow").attr("ms.cmpgrp","body");$(".primaryMainColumn").attr("ms.cmpgrp","body");$(".primaryThinColumn").attr("ms.cmpgrp","rightrail");$(".kb,.primaryThinColumn").each(function(){$(this).attr({"ms.pgarea":"content","ms.scnct":"TechSupport"});});$(".kbSurvey").attr("ms.pgarea","content");$(".functionButton a,#kb_translateBtn").each(function(){if($(this).attr("id")=="kb_translateBtn"){cmpTyp="dropdwn";ti="translate";}else{cmpTyp="link";var biTitle=$(this).attr("bi:title");ti=(biTitle&&biTitle.indexOf("javascript")==-1)?biTitle:$.trim($(this).text());ti=ti.toLowerCase();}
$(this).attr({"ms.cmpnm":ti,"ms.cmptyp":cmpTyp,'ms.title':ti,"ms.ea_action":ti,"ms.ea_name":"Website","ms.ea_offer":"KB","ms.interactiontype":"1"});});$("#kb_translatePanel .column a").each(function(){setMsTitle(this,"translate","link","1");});$("#kb_translatePanel_closeBtn").each(function(){setMsTitle(this,"translate","dropdwn","1");});$("a[id*='Disclaimer_link']").each(function(){ti=$(this).attr("bi:title")||$.trim($(this).text());ti=ti.toLowerCase();$(this).attr({"ms.cmpnm":"disclaimer","ms.cmptyp":"link",'ms.title':ti,"ms.interactiontype":"1"});});$("#mt_disclaimer_link").each(function(){$(this).attr({"ms.cmpnm":"mt_disclaimer","ms.cmptyp":"link",'ms.title':"machine translate disclaimer","ms.interactiontype":"1"});});$("#mt_sbs_link").each(function(){$(this).attr({"ms.cmpnm":"mt_sidebyside","ms.cmptyp":"link",'ms.title':"side by side view","ms.interactiontype":"1"});});$("div.adWrapper a").each(function(){ti=$(this).attr("bi:title")||$.trim($(this).text());ti=ti.toLowerCase();$(this).attr({"ms.cmpnm":"impnotice","ms.cmptyp":"link",'ms.title':ti,"ms.interactiontype":"1"});});$("#mt_article_properties a").each(function(){setMsTitle(this,"prdlink","link","1");});$("#kb_warning_divider a").each(function(){setMsTitle(this,"systip","link","1");});Bootstrapper.ajaxListener.create(function(){var n=$(".notesbox .notice");if(n&&n.length>0){return n;}},function(n){n=$(n).find('a');ti=$(n).attr("bi:title")||$.trim($(n).text());ti=ti.toLowerCase();$(n).attr({"ms.cmpnm":"notice","ms.cmptyp":"link","ms.title":ti,"ms.interactiontype":"1"});});$(".sbody a[bi\\:title]:not[ms.title]").each(function(){var cmpnm;var subTitle=$(this).parents('.sbody').prevAll(".subTitle")[0];if(subTitle){cmpnm=$(subTitle).find("a").attr("bi:title")||$.trim($(subTitle).find("a").text()).toLowerCase();}
if(!cmpnm){cmpnm="ref";}
setMsTitle(this,cmpnm,'link',"1");});$("#kb_hotfix_link").each(function(){var ti=$(this).attr("bi:title")||$.trim($(this).text());ti=ti.toLowerCase();$(this).attr({"ms.cmpnm":"hotfix-download","ms.cmptyp":"link","ms.title":ti,"ms.interactiontype":"1","ms.ea_action":"download","ms.ea_name":"Website","ms.ea_offer":"hotfix","ms.scnct":"Download"});});var i;Bootstrapper.ajaxListener.create(function(){var n=$("#tocDiv li");if(n&&n.length>0){return n;}},function(n){n=$(n).find('a');ti=$(n).attr("bi:title")||$.trim($(n).text());ti=ti.toLowerCase();$(n).attr({"ms.cmpnm":"in this article","ms.cmptyp":"link","ms.title":ti,"ms.interactiontype":"1"});});$("#kb_expandcollapseall a").each(function(){var ti;var intType;if($(this).hasClass("expandalltext")){ti="show";intType="14";}
else if($(this).hasClass("collapsealltext")){ti="hide";intType="15";}
$(this).attr({"ms.cmpnm":"collapse-top","ms.cmptyp":"control","ms.title":ti,"ms.interactiontype":intType});$(this).click(function(){var ti;var intType;if($(this).hasClass("expandalltext")){ti="show";intType="14";}
else if($(this).hasClass("collapsealltext")){ti="hide";intType="15";}
$(this).attr({"ms.title":ti,"ms.interactiontype":intType});});});Bootstrapper.ajaxListener.create(function(){var n=$("#kb_section h2,.kbSurvey h2");if(n&&n.length>0){return n;}},function(n){cmpnm=$(n).find('a').attr('bi:title')||$(n).find('a').text();cmpnm=cmpnm.toLowerCase();var ti;var intType;if($(n).hasClass("kb_tabs_toggle_closed")){ti="hide";intType="15";}
else{ti="show";intType="14";}
$(n).attr({"ms.cmpnm":cmpnm,"ms.cmptyp":"control","ms.title":ti,"ms.interactiontype":intType});$(n).click(function(event){var evt=event||window.event;var e,check;if(evt){try{e=evt.srcElement||evt.target;check=MscomIsInList(e.tagName);while(e.tagName&&check===0){e=e.parentElement||e.parentNode;if(e.tagName){check=MscomIsInList(e.tagName);}}}catch(err){}
var cmpnm=$(this).find('a').attr('bi:title')||$(this).find('a').text();cmpnm=cmpnm.toLowerCase();var ti;var intType;if($(n).hasClass("kb_tabs_toggle_closed")){ti="hide";intType="15";}
else{ti="show";intType="14";}
$(n).attr({"ms.title":ti,"ms.interactiontype":intType});if(check===0){MscomCustomEvent("ms.cmpgrp=body","ms.cmpnm="+cmpnm,"ms.cmptyp=control","ms.title="+ti,"ms.interactiontype="+intType);}}});});Bootstrapper.ajaxListener.create(function(){var n=$(".CIP_SectionHead");if(n&&n.length>0){return n;}},function(n){cmpnm=$(n).find('a').attr('bi:title')||$(n).find('a').text();cmpnm=cmpnm.toLowerCase();var ti;var intType;if($(n).hasClass("CIP_SectionHeadCollapse")){ti="collapse";intType="15";}
else{ti="expand";intType="14";}
$(n).attr({"ms.cmpnm":cmpnm,"ms.cmptyp":"control","ms.title":ti,"ms.interactiontype":intType});$(n).click(function(event){var cmpnm=$(this).find('a').attr('bi:title')||$(this).find('a').text();cmpnm=cmpnm.toLowerCase();var ti;var intType;if($(n).hasClass("CIP_SectionHeadCollapse")){ti="collapse";intType="15";}
else{ti="expand";intType="14";}
$(n).attr({"ms.title":ti,"ms.interactiontype":intType});MscomCustomEvent("ms.cmpgrp=body","ms.cmpnm="+cmpnm,"ms.cmptyp=control","ms.title="+ti,"ms.interactiontype="+intType);});});Bootstrapper.ajaxListener.create(function(){var n=$(".kb_outergraphicwrapper");if(n&&n.length>0){return n;}},function(n){cmpnm="article_graphic";var ti;var intType;if($(n).hasClass("kb_outergraphicwrapper_closed")){ti="collapse";intType="15";}
else{ti="expand";intType="14";}
$(n).attr({"ms.cmpnm":cmpnm,"ms.cmptyp":"control","ms.title":ti,"ms.interactiontype":intType});$(n).click(function(event){var evt=event||window.event;var e,check;if(evt){try{e=evt.srcElement||evt.target;check=MscomIsInList(e.tagName);while(e.tagName&&check===0){e=e.parentElement||e.parentNode;if(e.tagName){check=MscomIsInList(e.tagName);}}}catch(err){}
var cmpnm="article_graphic";var intType;if($(n).hasClass("kb_outergraphicwrapper_closed")){ti="collapse";intType="15";}
else{ti="expand";intType="14";}
$(n).attr({"ms.title":ti,"ms.interactiontype":intType});if(check===0){MscomCustomEvent("ms.cmpgrp=body","ms.cmpnm="+cmpnm,"ms.cmptyp=control","ms.title="+ti,"ms.interactiontype="+intType);}}});});$(".topOfPage").each(function(){var cmpnm;var cmpAnchor=$(this).parent('div.sbody').prevAll('h2').find('a');if(cmpAnchor){cmpnm=cmpAnchor.attr('bi:title')||$.trim(cmpAnchor.text()).toLowerCase();}
if(!cmpnm){cmpnm="bottom-page";}
$("a",$(this)).each(function(){ti=$(this).attr("bi:title")||$.trim($(this).text());ti=ti.toLowerCase();$(this).attr({"ms.cmpnm":cmpnm,"ms.cmptyp":"control","ms.title":ti,"ms.interactiontype":"11"});});});Bootstrapper.ajaxListener.create(function(){var n=$("#relatedContent a");if(n&&n.length>0){return n;}},function(n){setMsTitle(n,"related articles","link","1");});Bootstrapper.ajaxListener.create(function(){var n=$("#relatedContentCommunity a");if(n&&n.length>0){return n;}},function(n){setMsTitle(n,"related community","link","1");});ti=$(".kbSurvey .questionBanner input").val()||'Yes';$(".kbSurvey .questionBanner input").click(function(b_ti){return function(){MscomCustomEvent('ms.cmpgrp=feedback','ms.pgarea=content','ms.cmpnm=feedback','ms.cmptyp=button','ms.title='+b_ti,'ms.interactiontype=1');};}(ti));$(".SURVEYINTROTEXT a").each(function(){setMsTitle(this,"give feedback","link","1");});})();}catch(e){Bootstrapper.reportException(e);}});});(window.callback80970=window.callback80970||Bootstrapper.new_fArray()).add(function(){Bootstrapper.setCurrentRuleId(80970);Bootstrapper.bindDOMParsed(function(){try{Bootstrapper.setCurrentRuleId(80971);(function(){var surveyId=Bootstrapper.TAG.surveyId;var quesId,queTxt,ansId,ansTxt,is_ranking;if(surveyId=="3590"){$(".QUESTIONCONTAINER").each(function(){quesId=$("INPUT[name='id']",this).val();is_ranking=$("INPUT[name='ranking']",this).length>0;switch(quesId){case'32862':queTxt="overall experience with microsoft community?";break;case'32863':queTxt="microsoft community experience impacted your opinions of microsoft?";break;case'32864':queTxt="get what you needed?";break;case'32865':queTxt="effort?";break;case'32866':queTxt="recommended microsoft product or service?";break;case'32867':queTxt="rate the overall quality?";break;case'32868':queTxt="reason for visit?";break;case'32869':queTxt="suggestion to improve?";break;default:queTxt="new question";break;}
$("input[type='radio'], input[type='checkbox']",this).each(function(){if(is_ranking){ansTxt=null;}else{ansTxt=null;ansId=$(this).attr("id");switch(ansId){case'56399':ansTxt="yes";break;case'56408':ansTxt="yes";break;case'56400':ansTxt="no";break;case'56409':ansTxt="no";break;case'56401':ansTxt="not sure yet";break;case'56402':ansTxt="not applicable";break;case'56403':ansTxt="far less than expected";break;case'56404':ansTxt="less than expected";break;case'56405':ansTxt="about what expected";break;case'56406':ansTxt="more than expected";break;case'56407':ansTxt="far more than expected";break;case'56410':ansTxt="dont know";break;case'56411':ansTxt="resolve technical problem";break;case'56412':ansTxt="learn how product, service works";break;case'56413':ansTxt="solve a billing or account problem";break;case'56414':ansTxt="other";break;default:ansTxt="new";break;}}
$(this).attr({'ms.scn':queTxt,'ms.scvalue':ansTxt});});$("textarea.ANSWERBOX",this).each(function(){$(this).attr({'ms.scn':queTxt});});});}else if(surveyId=="3569"||surveyId=="3574"){$(".QUESTIONCONTAINER").each(function(){quesId=$("INPUT[name='id']",this).val();is_ranking=$("INPUT[name='ranking']",this).length>0;switch(quesId){case'32694':queTxt="Reason for visit?";break;case'32697':queTxt="How satisfied?";break;case'32695':queTxt="Find information, resources?";break;case'32696':queTxt="Effort?";break;case'32724':queTxt="Reason for visit?";break;case'32726':queTxt="How satisfied?";break;case'32725':queTxt="Find information, resources?";break;case'32751':queTxt="Effort?";break;case'32698':queTxt="Why Dissatisfied?";break;case'32693':queTxt="Suggestion to improve";break;case'32723':queTxt="Suggestion to improve";break;case'32692':queTxt="Suggestion to improve";break;case'32722':queTxt="Suggestion to improve";break;default:queTxt="new question";break;}
$("input[type='radio'], input[type='checkbox']",this).each(function(){if(is_ranking){ansTxt=null;}else{ansTxt=null;ansId=$(this).attr("id");switch(ansId){case'55725':ansTxt="Resolve technical problem";break;case'55708':ansTxt="Download, install, activate, update";break;case'55710':ansTxt="Learn how product, service works";break;case'55707':ansTxt="Buy product, service";break;case'55726':ansTxt="Solve a billing or account problem";break;case'55793':ansTxt="Resolve technical problem";break;case'55794':ansTxt="Download, install, activate, update";break;case'55792':ansTxt="Learn how product, service works";break;case'55791':ansTxt="Buy product, service";break;case'55795':ansTxt="Solve a billing or account problem";break;case'55789':ansTxt="Feedback";break;case'55723':ansTxt="Other";break;case'55797':ansTxt="Other";break;case'55730':ansTxt="Very satisfied";break;case'55728':ansTxt="Somewhat satisfied";break;case'55727':ansTxt="Somewhat dissatisfied";break;case'55729':ansTxt="Very dissatisfied";break;case'55716':ansTxt="Yes";break;case'55719':ansTxt="Some";break;case'55713':ansTxt="No";break;case'55790':ansTxt="No";break;case'55714':ansTxt="Very low";break;case'55711':ansTxt="Low";break;case'55712':ansTxt="Moderate";break;case'55709':ansTxt="High";break;case'55715':ansTxt="Very high";break;case'55718':ansTxt="I couldn't find";break;case'55720':ansTxt="Found, but didn't understand";break;case'55721':ansTxt="Found, but didn't answer, resolve";break;case'55722':ansTxt="Wanted to contact someone";break;case'55717':ansTxt="Finding the answer was harder";break;case'55796':ansTxt="Finding the answer was harder";break;case'55724':ansTxt="Other";break;case'55798':ansTxt="Other";break;default:ansTxt="new";break;}}
$(this).attr({'ms.scn':queTxt,'ms.scvalue':ansTxt});});$("textarea.ANSWERBOX",this).each(function(){$(this).attr({'ms.scn':queTxt});});});}else if(surveyId=="3563"){$(".QUESTIONCONTAINER").each(function(){quesId=$("INPUT[name='id']",this).val();is_ranking=$("INPUT[name='ranking']",this).length>0;if(quesId=='32328'){queTxt="Information helpful?";}else{queTxt="new question";}
$("input[type='radio'], input[type='checkbox']",this).each(function(){if(is_ranking){ansTxt=null;}else{ansTxt=null;ansId=$(this).attr("id");switch(ansId){case'57185':ansTxt="Yes";break;case'54975':ansTxt="Somewhat";break;case'54974':ansTxt="No";break;default:ansTxt="new";break;}}
$(this).attr({'ms.scn':queTxt,'ms.scvalue':ansTxt});});$("textarea.ANSWERBOX",this).each(function(){$(this).attr({'ms.scn':queTxt});});});}else if(surveyId=="3530"){$(".QUESTIONCONTAINER").each(function(){quesId=$("INPUT[name='id']",this).val();is_ranking=$("INPUT[name='ranking']",this).length>0;switch(quesId){case'31543':queTxt="How satisfied?";break;case'31533':queTxt="Find information, resources?";break;case'31530':queTxt="Reason for visit?";break;case'31538':break;case'31532':break;case'31534':break;case'31536':break;case'31547':break;default:queTxt="new question";break;}
$("input[type='radio'], input[type='checkbox']",this).each(function(){if(is_ranking){ansTxt=null;}else{ansTxt=null;ansId=$(this).attr("id");switch(ansId){case'52775':ansTxt="Very satisfied";break;case'52776':ansTxt="Somewhat satisfied";break;case'52777':ansTxt="Somewhat dissatisfied";break;case'52778':ansTxt="Very dissatisfied";break;case'52764':ansTxt="Yes";break;case'52762':ansTxt="Some";break;case'52761':ansTxt="No";break;case'52763':ansTxt="Don't know";break;case'52754':ansTxt="Tech - Specific Error";break;case'52757':ansTxt="Tech - Virus, security, password";break;case'52758':ansTxt="Tech - Other";break;case'52771':ansTxt="Download or update software";break;case'52772':ansTxt="Download a template";break;case'52765':ansTxt="Accomplish specific task";break;case'52766':ansTxt="Learn about sepcific feature";break;case'52767':ansTxt="Learn about microsoft products";break;case'52768':ansTxt="Activate, find product key, Install";break;case'52770':ansTxt="Billing or Purchase issues";break;case'52773':ansTxt="Connect, collaborate, or share";break;case'52774':ansTxt="Submit bugs/feedback/questions";break;case'52780':ansTxt="Others";break;default:ansTxt="new";break;}}
$(this).attr({'ms.scn':queTxt,'ms.scvalue':ansTxt});});$("textarea.ANSWERBOX",this).each(function(){$(this).attr({'ms.scn':queTxt});});});}else if(surveyId=="3626"){$(".QUESTIONCONTAINER").each(function(){quesId=$("INPUT[name='id']",this).val();is_ranking=$("INPUT[name='ranking']",this).length>0;switch(quesId){case'33875':queTxt="Reason for visit?";break;case'33876':queTxt="How satisfied?";break;case'33877':queTxt="Find information, resources?";break;case'33878':queTxt="Effort?";break;case'33879':queTxt="Why Dissatisfied?";break;case'33880':queTxt="Suggestion to improve";break;case'33881':queTxt="Suggestion to improve";break;default:queTxt="new question";break;}
$("input[type='radio'], input[type='checkbox']",this).each(function(){if(is_ranking){ansTxt=null;}else{ansTxt=null;ansId=$(this).attr("id");switch(ansId){case'57802':ansTxt="Resolve technical problem";break;case'57803':ansTxt="Download, install, activate, update";break;case'57804':ansTxt="Learn how product, service works";break;case'57805':ansTxt="Buy product, service";break;case'57806':ansTxt="Solve a billing or account problem";break;case'57807':ansTxt="Other";break;case'57808':ansTxt="Very satisfied";break;case'57809':ansTxt="Somewhat satisfied";break;case'57810':ansTxt="Somewhat dissatisfied";break;case'57811':ansTxt="Very dissatisfied";break;case'57813':ansTxt="Yes";break;case'57814':ansTxt="Some";break;case'57815':ansTxt="No";break;case'57817':ansTxt="Very low";break;case'57818':ansTxt="Low";break;case'57819':ansTxt="Moderate";break;case'57820':ansTxt="High";break;case'57821':ansTxt="Very high";break;case'57822':ansTxt="I couldn't find";break;case'57823':ansTxt="Found, but didn't understand";break;case'57824':ansTxt="Found, but didn't answer, resolve";break;case'57825':ansTxt="Wanted to contact someone";break;case'57826':ansTxt="Finding the answer was harder";break;case'57827':ansTxt="Other";break;default:ansTxt="new";break;}}
$(this).attr({'ms.scn':queTxt,'ms.scvalue':ansTxt});});$("textarea.ANSWERBOX",this).each(function(){$(this).attr({'ms.scn':queTxt});});});}else if(surveyId=="3613"){$(".QUESTIONCONTAINER").each(function(){quesId=$("INPUT[name='id']",this).val();is_ranking=$("INPUT[name='ranking']",this).length>0;switch(quesId){case'33651':queTxt="Reason for visit?";break;case'33540':queTxt="How satisfied?";break;case'33541':queTxt="Find information, resources?";break;case'33542':queTxt="Effort?";break;case'33543':queTxt="Size of the Business?";break;default:queTxt="new question";break;}
$("input[type='radio'], input[type='checkbox']",this).each(function(){if(is_ranking){ansTxt=null;}else{ansTxt=null;ansId=$(this).attr("id");switch(ansId){case'57373':ansTxt="Resolve technical problem";break;case'57374':ansTxt="Download, install, activate, update";break;case'57375':ansTxt="Learn special taks using product, service";break;case'57376':ansTxt="Learn special feature in product, service";break;case'57377':ansTxt="Other";break;case'57167':ansTxt="Very satisfied";break;case'57168':ansTxt="Somewhat satisfied";break;case'57169':ansTxt="Somewhat dissatisfied";break;case'57170':ansTxt="Very dissatisfied";break;case'57171':ansTxt="Yes";break;case'57172':ansTxt="Some not all";break;case'57173':ansTxt="No";break;case'57174':ansTxt="Don't know";break;case'57175':ansTxt="Very low";break;case'57176':ansTxt="Low";break;case'57177':ansTxt="Moderate";break;case'57178':ansTxt="High";break;case'57179':ansTxt="Very high";break;case'57180':ansTxt="1 to 4";break;case'57181':ansTxt="5 to 24";break;case'57182':ansTxt="25 to 49";break;case'57183':ansTxt="50 to 249";break;case'57184':ansTxt="250 or more";break;default:ansTxt="new";break;}}
$(this).attr({'ms.scn':queTxt,'ms.scvalue':ansTxt});});$("textarea.ANSWERBOX",this).each(function(){$(this).attr({'ms.scn':queTxt});});});}else if(surveyId=="3518"){$(".QUESTIONCONTAINER").each(function(){quesId=$("INPUT[name='id']",this).val();is_ranking=$("INPUT[name='ranking']",this).length>0;switch(quesId){case'32964':queTxt="Reason for visit?";break;case'32966':queTxt="How satisfied?";break;case'33359':queTxt="Find information, resources?";break;case'33360':queTxt="Effort?";break;case'33358':queTxt="Size of the Business?";break;default:queTxt="new question";break;}
$("input[type='radio'], input[type='checkbox']",this).each(function(){if(is_ranking){ansTxt=null;}else{ansTxt=null;ansId=$(this).attr("id");switch(ansId){case'56585':ansTxt="Resolve technical problem";break;case'56586':ansTxt="Download, install, activate, update";break;case'56587':ansTxt="Learn special taks using product, service";break;case'56588':ansTxt="Learn special feature in product, service";break;case'56589':ansTxt="Other";break;case'56591':ansTxt="Very satisfied";break;case'56593':ansTxt="Somewhat satisfied";break;case'56594':ansTxt="Somewhat dissatisfied";break;case'56595':ansTxt="Very dissatisfied";break;case'56999':ansTxt="Yes";break;case'57000':ansTxt="Some not all";break;case'56998':ansTxt="No";break;case'56996':ansTxt="Don't know";break;case'57005':ansTxt="Very low";break;case'57002':ansTxt="Low";break;case'57003':ansTxt="Moderate";break;case'57001':ansTxt="High";break;case'57004':ansTxt="Very high";break;case'57006':ansTxt="1 to 4";break;case'57009':ansTxt="5 to 24";break;case'57007':ansTxt="25 to 49";break;case'57010':ansTxt="50 to 249";break;case'57008':ansTxt="250 or more";break;default:ansTxt="new";break;}}
$(this).attr({'ms.scn':queTxt,'ms.scvalue':ansTxt});});$("textarea.ANSWERBOX",this).each(function(){$(this).attr({'ms.scn':queTxt});});});}else if(surveyId=="1809"||surveyId=="1686"||surveyId=="132"){$(".QUESTIONCONTAINER").each(function(){quesId=$("INPUT[name='id']",this).val();is_ranking=$("INPUT[name='ranking']",this).length>0;switch(quesId){case'12616':queTxt="Information helpful?";break;case'10576':queTxt="Effort?";break;case'12617':case'9087':queTxt="Suggestion to improve?";break;case'9088':queTxt="Information solve problem?";break;case'9086':queTxt="Information relevent?";break;default:queTxt="new question";break;}
$("input[type='radio'], input[type='checkbox']",this).each(function(){if(is_ranking){ansTxt=null;}else{ansTxt=null;ansId=$(this).attr("id");switch(ansId){case'125':case'14471':ansTxt='Yes';break;case'126':case'14472':ansTxt='No';break;case'14473':ansTxt='dont know';break;case'18874':ansTxt='Somewhat';break;case'16305':ansTxt='Very low';break;case'16306':ansTxt='Low';break;case'16307':ansTxt='Moderate';break;case'16308':ansTxt='High';break;case'16309':ansTxt='Very high';break;default:ansTxt="new";break;}}
$(this).attr({'ms.scn':queTxt,'ms.scvalue':ansTxt});});$("textarea.ANSWERBOX",this).each(function(){$(this).attr({'ms.scn':queTxt});});});}else if(surveyId=="3762"){$(".QUESTIONCONTAINER").each(function(){quesId=$("INPUT[name='id']",this).val();is_ranking=$("INPUT[name='ranking']",this).length>0;switch(quesId){case'35422':queTxt="resources help resolve issue?";break;case'35423':queTxt="microsoft support easy to use?";break;case'35424':queTxt="comments about experience";break;default:queTxt="new question";break;}
$("input[type='radio'], input[type='checkbox']",this).each(function(){if(is_ranking){ansTxt=null;}else{ansTxt=null;ansId=$(this).attr("id");switch(ansId){case'62828':ansTxt='Yes';break;case'62829':ansTxt='found some not all';break;case'62830':ansTxt='No';break;case'62831':ansTxt='Easy';break;case'62832':ansTxt='Moderate';break;case'62833':ansTxt='Difficult';break;default:ansTxt="new";break;}}
$(this).attr({'ms.scn':queTxt,'ms.scvalue':ansTxt});});$("textarea.ANSWERBOX",this).each(function(){$(this).attr({'ms.scn':queTxt});});});}}());}catch(e){Bootstrapper.reportException(e);}});});Bootstrapper.bindDOMParsed(function(){try{Bootstrapper.setCurrentRuleId(80970);var isReferrerSet=false;var ref="none";var REGEX_SURVEYPG=/\/(common|fms)\/.*survey.*/i;var TEXT_LIMIT=100;var MS_OPT_TEXT="ms.verbatim";function isSSBSurvey(){return(Bootstrapper.TAG.surveyId=="3613"||Bootstrapper.TAG.surveyId=="3518");}
function setReferrerValue(){try{var targetDomain=window.targetDomain;ref=(targetDomain==undefined)?"missing":targetDomain;}catch(e){}
if(!isReferrerSet&&REGEX_SURVEYPG.test(window.location.pathname)){Bootstrapper.TMDL.setMeta(Bootstrapper.TMDL.BIParameters.site.ref,Bootstrapper.TMDL.collectors.WEDCS.BIMap,ref);Bootstrapper.TMDL.setMeta(Bootstrapper.TMDL.BIParameters.site.referrercontenttype,Bootstrapper.TMDL.collectors.WEDCS.BIMap,ref);isReferrerSet=true;}}
function triggerSurveyEvent(q_params){var params=[];if(q_params["ms.track"]){q_params["ms.track"]="true";}
for(var a in q_params){params.push(a.toLowerCase()+"="+q_params[a]);}
MscomCustomEvent.apply(undefined,params);}
function tagSurveyChoiceAns(ques,is_ranking,q_params){var params;$("input[type='radio']:checked",ques).each(function(){params={};elm_nm=$(this).attr("name");$(this.attributes).each(function(){nm=this.nodeName;va=this.nodeValue;if(nm.toLowerCase().substr(0,3)=="ms."){if(!is_ranking&&/ms\.scvalue/i.test(nm)&&(va.toLowerCase()=="other"||va.toLowerCase()=="others"||/don(|')t know/i.test(va.toLowerCase()))&&$(".OPTIONALTEXTBOX[name='"+elm_nm+"']")){var optiontext=$(".OPTIONALTEXTBOX[name='"+elm_nm+"']").val();if(isSSBSurvey()){params[MS_OPT_TEXT]=optiontext.substring(0,TEXT_LIMIT);}else{va=va+"-"+optiontext;}}
params[nm]=va;}});if(is_ranking){params["ms.scvalue"]=$(this).val();}
params["ms.srv_resp"]=$(this).attr("id");params["ms.interactiontype"]=19;triggerSurveyEvent($.extend(params,q_params));});}
function tagSurveyCheckAns(ques,q_params){if($(".CHOICEROW input[type='checkbox']",ques).length>0){var chkd,other="",ms_srv_respAll="",chkbxAns="";chkd=false;$(".CHOICEROW input[type='checkbox']",ques).each(function(){if($(this).is(':checked')){if($(this).attr("ms.scvalue")){if(($(this).attr("ms.scvalue").toLowerCase()=="other"||$(this).attr("ms.scvalue").toLowerCase()=="others")&&$(".OPTIONALTEXTBOX",this)){other=$(this).parents(".QUESTIONCONTAINER").find(".OPTIONALTEXTBOX").val();if(other==undefined){other="";}}
chkbxAns=chkbxAns+$(this).attr("ms.scvalue")+"|";}
ms_srv_respAll=ms_srv_respAll+$(this).attr("id")+"|";chkd=true;}else if(!$(this).is(':checked')){if($(this).attr("ms.scvalue")){chkbxAns=chkbxAns+"-"+"|";}
ms_srv_respAll=ms_srv_respAll+"-"+"|";}});if(chkd){var params=[];$(".CHOICEROW input[type='checkbox']",ques).each(function(){if($(this).is(':checked')){$(this.attributes).each(function(){nm=this.nodeName;va=this.nodeValue;if(nm.toLowerCase().substr(0,3)=="ms."){params[nm]=va;}});}});if(chkbxAns.length>0){chkbxAns=chkbxAns.substring(0,chkbxAns.length-1);if(isSSBSurvey()){params[MS_OPT_TEXT]=other.length>0?other.substring(0,TEXT_LIMIT):null;}else{chkbxAns=chkbxAns+(other.length>0?"-"+other:"");}
params["ms.scvalue"]=chkbxAns;}
ms_srv_respAll=ms_srv_respAll.substring(0,ms_srv_respAll.length-1);params["ms.srv_resp"]=ms_srv_respAll;params["ms.interactiontype"]=19;triggerSurveyEvent($.extend(params,q_params));}}}
function tagSurveyTextAns(ques,q_params){if($("textarea.ANSWERBOX",ques).length>0){var params,ans;$("textarea.ANSWERBOX",ques).each(function(){ans=$(this).val();if(ans&&ans.length>0){params=[];$(this.attributes).each(function(){nm=this.nodeName;va=this.nodeValue;if(nm.toLowerCase().substr(0,3)=="ms."){params[nm]=va;}});if($(this).attr("ms.scn")&&$(this).attr("ms.scn").length>0){params["ms.scvalue"]=ans;}
params["ms.interactiontype"]=19;triggerSurveyEvent($.extend(params,q_params));}});}}
function tagSurveyQuestion(survey_page_id){if(Bootstrapper.TAG.surveyDefaultEvent){var params,quesId,type,is_ranking;params={};params["ms.cmpgrp"]="body";params["ms.scnum"]=Bootstrapper.TAG.surveyId;params["ms.srv_id"]=Bootstrapper.TAG.surveyId;params["ms.srv_v"]="";$(".QUESTIONCONTAINER","#"+survey_page_id).each(function(){quesId=$("INPUT[name='id']",this).val();type=$("INPUT[name='type']",this).val().toUpperCase();is_ranking=$("INPUT[name='ranking']",this).length>0;params["ms.srv_v"]=quesId;if(type=="CHOICE"||type=="CHOICE-HOR"){tagSurveyChoiceAns(this,is_ranking,params);}else if(type=="CHECK-LIST"){tagSurveyCheckAns(this,params);}else if(type=="TEXT-BLOCK"){tagSurveyTextAns(this,params);}else{tagSurveyChoiceAns(this,is_ranking,params);tagSurveyCheckAns(this,params);tagSurveyTextAns(this,params);}});}}
(function(){var i,j,ti,intType,surveyId,surv_v,surv_r,elm_id;var scid=Bootstrapper.TAG.getQueryValue("scid",window.location.href);surveyId=scid.split(";")[2];if((surveyId==null||surveyId.length<1)&&kbSurvey){surveyId=kbSurvey.getSurveyId();}else if((surveyId==null||surveyId.length<1)&&_ms_support_fms_surveyConfig){surveyId=_ms_support_fms_surveyConfig.survey.id;}
Bootstrapper.TAG.surveyId=surveyId;Bootstrapper.TAG.surveyDefaultEvent=true;$(".QUESTIONCONTAINER").each(function(){surv_v=$(this).find("INPUT[name='id']").val();$(this).attr({'ms.track':'false'});});i=1;j=$("#SURVEYSECTIONCONTAINER .SURVEYSECTION").length;$("#SURVEYSECTIONCONTAINER .SURVEYSECTION").each(function(){elm_id=$(this).attr("id");if(i==j){intType=2;ti="submit";}else{intType=9;ti="next";}
$(".NAVIGATION INPUT[name='next']",this).each(function(){$(this).attr({'ms.cmpnm':ti,'ms.cmptyp':'button','ms.interactiontype':intType,"ms.scnum":surveyId,"ms.srv_id":surveyId});if(navigator.appVersion.indexOf("MSIE")!=-1){Bootstrapper.unobtrusiveAddEvent(this,"onclick",function(id){return function(){setReferrerValue();tagSurveyQuestion(id);};}(elm_id));}else{Bootstrapper.unobtrusiveAddEvent(this,"onmousedown",function(id){return function(){setReferrerValue();tagSurveyQuestion(id);};}(elm_id));}});i++;});}());;callback80970.exec();}catch(e){Bootstrapper.reportException(e);}});;