var gfc_vo=osapi,gfc_wo="ceil";gfc_1[gfc_].ni=gfc_qd(21,function(a,b,c){return a?c<b?[]:a[gfc_yc](gfc_d.min(b,a[gfc_B]),gfc_d.min(c,a[gfc_B])):[]});gfc_1[gfc_].share=gfc_qd(19,function(){gfc_Un();return!1});gfc_1[gfc_].vf=gfc_qd(17,function(){return this.Eb.pop()});gfc_1[gfc_].Gi=gfc_qd(16,function(){var a=this.wd;a.valid?(this.d=this.Bg(this.wd),this.Nh(a[gfc_9c])):(this.wd=null,this.render(a.actions,a[gfc_9c],a.params));this.Ag()});
gfc_pa(gfc_N[gfc_],gfc_qd(3,function(){this.x=gfc_d[gfc_wo](this.x);this.y=gfc_d[gfc_wo](this.y);return this}));gfc_pa(gfc_nf[gfc_],gfc_qd(2,function(){gfc_na(this,gfc_d[gfc_wo](this[gfc_i]));gfc_Ga(this,gfc_d[gfc_wo](this[gfc_u]));return this}));gfc_pa(gfc_ah[gfc_],gfc_qd(1,function(){this.top=gfc_d[gfc_wo](this.top);gfc_Ha(this,gfc_d[gfc_wo](this[gfc_oc]));gfc_Da(this,gfc_d[gfc_wo](this[gfc_$b]));gfc_Ma(this,gfc_d[gfc_wo](this[gfc_z]));return this}));
gfc_pa(gfc_bh[gfc_],gfc_qd(0,function(){gfc_Ma(this,gfc_d[gfc_wo](this[gfc_z]));this.top=gfc_d[gfc_wo](this.top);gfc_na(this,gfc_d[gfc_wo](this[gfc_i]));gfc_Ga(this,gfc_d[gfc_wo](this[gfc_u]));return this}));
var gfc_xo=function(a){return a=gfc_b.friendconnect_serverBase+"/friendconnect/favicon?url="+escape(a)},gfc_7=function(a,b,c){this.Ga();this.lr();var d=new gfc_R;d.set("members",{action:this.tu,callback:this.qt});d.set("member-page",{action:this.su,callback:this.pt});d.set("blocked-member-page",{action:this.mu,callback:this.lt});d.set("profile-friends-page",{action:this.yu,callback:this.ut});d.set("sitesData",{action:this.Gu,callback:this.yt});d.set("viewerFriends",{action:this.Lu,callback:this.At});
d.set("profileData",{action:this.xu,callback:this.tt});d.set("blockUser",{action:this.lu,callback:this.kt});d.set("unblockUser",{action:this.Ju,callback:this.zt});d.set("profileFriends",{action:this.zu,callback:this.vt});d.set("activityData",{action:this.Ff,callback:this.gd});d.set("sendFriendRequest",{action:this.Fu,callback:this.xt});d.set("sendFriendRequestResponse",{action:this.pu,callback:this.Zl});d.set("deleteActivity",{action:this.Gf,callback:this.gd});d.set("requestAndProcessViewerNumWaitingMessages",
{action:this.Mu,callback:this.Ct});d.set("requestPromo",{action:this.Au,callback:this.wt});this.lb=null;this.ix=new gfc_1n("fc-members-options-menu",gfc_K(this.Os,this),gfc_K(this.Ns,this),gfc_K(this.Ps,this),0,gfc_b.friendconnect_serverBase,this.f("ENDCAP_LINK_COLOR")||"0000cc",this.f("CONTENT_TEXT_COLOR")||"000000");this.Tv=!1;this.Ba=10;this.of=15;this.jn=10;var e=gfc_Gh(gfc_kh()),f=gfc_yo;this.Rb=3;this.mc=8;this.zm=null;this.la=this.mc*this.Rb;this.slimTopCapHeight=19;this.tinyTopCapHeight=8;
this.isMessagingEnabled=a;this.isPromosEnabled=b;this.isSocialShareEnabled=c;this.numWaitingMessages=0;this.promoCode=-1;this.promoHtml=null;this.Lb=new gfc_Yn;this.Hh()&&(a=(a=this.f(f.FACE_SIZE))?gfc_ga(a):32,a+=6,this.Rb=gfc_d[gfc_4a]((e[gfc_i]-10)/a),e=340,e=this.f(f.HEIGHT),b=this.f(f.NUMBER_ROWS),f=27,b?(this.mc=gfc_ga(b),e=this.mc*a,this.zm=e+f):e&&(e=gfc_ga(e)-96,this.mc=gfc_d.max(2,gfc_d[gfc_4a](e/a)),this.zm=this.mc*a+f),this.la=this.mc*this.Rb);gfc_1[gfc_G](this,d)};gfc_7.inherits(gfc_1);
gfc_Ba(gfc_7[gfc_],function(){gfc_7.i[gfc_t][gfc_G](this);gfc_vn("start");var a=gfc_a[gfc_r][gfc_Ic](),b=gfc_ca();(a=b.profileId||a.profileId)?(b={},b[gfc_e[gfc_x][gfc_q].ID]=a,a=new gfc_e[gfc_x](b),this.render(["profileData","profileFriends","activityData"],"profile",{person:a})):(a=["members","viewerFriends"],this.isMessagingEnabled&&a[gfc_v]("requestAndProcessViewerNumWaitingMessages"),this.isPromosEnabled&&!this.Hb()&&a[gfc_v]("requestPromo"),this.render(a,"faces"))});gfc_7[gfc_].e={};
gfc_7[gfc_].Ga=function(){this.e.MSG_SITE_MEMBERS="Miembros";this.e.MSG_BE_THE_FIRST="\u00a1S\u00e9 el primero!";this.e.MSG_NO_SITE_MEMBERS="Todav\u00eda no hay miembros.";this.e.MSG_ALL_SITE_MEMBERS="Todos los miembros";this.e.MSG_ALL_BLOCKED_MEMBERS="Todos los miembros bloqueados";this.e.MSG_NO_BLOCKED_MEMBERS="No has bloqueado a ning\u00fan miembro.";this.e.MSG_YOUR_FRIENDS="Tus amigos";this.e.MSG_ALL_YOUR_FRIENDS="Todos tus amigos";this.e.MSG_JFJ="Participa y con\u00e9ctate con otros.";this.e.MSG_MANAGE=
"Administrar miembros";this.e.MSG_SETTINGS="Configuraci\u00f3n";this.e.MSG_OPTIONS="Opciones";this.e.MSG_MEMBERS_SHARE="Comparte esta p\u00e1gina";this.e.MSG_BACK="Atr\u00e1s";this.e.MSG_BACK_TO_TOP="Inicio";this.e.MSG_VIEW_MY_PROFILE="Ver mi perfil";this.e.MSG_ABOUT_ME="Acerca de m\u00ed";this.e.MSG_MORE="M\u00e1s \u00bb";this.e.MSG_SHOW_BLOCKED="Mostrar a los miembros bloqueados \u00bb";this.e.MSG_SHOW_ALL="\u00ab Mostrar a todos los miembros";this.e.MSG_LINK_IN_NETWORKS="Conectar tus redes sociales";
this.e.MSG_ACTIVITIES="Actividades";this.e.MSG_ALL_ACTIVITIES="M\u00e1s actividades";this.e.MSG_DELETE_THIS="Eliminar";this.e.MSG_SITES="Sitios en los que participo";this.e.MSG_ALL_SITES="M\u00e1s sitios en los que participo";this.e.MSG_LINKS="Enlaces";this.e.MSG_ALL_LINKS="M\u00e1s enlaces";this.e.MSG_NO_ACTIVITIES="No hay actividades para mostrar.";this.e.MSG_ADD_AS_FRIEND="A\u00f1adir como amigo/a";this.e.MSG_SEND_MESSAGE="Enviar un mensaje";this.e.MSG_BLOCK_USER="Bloquear a este usuario";this.e.MSG_UNBLOCK_USER=
"Desbloquear a este usuario";this.e.MSG_USER_IS_ADMIN="Administrador";this.e.MSG_JOIN="Participar en este sitio";this.e.MSG_OR="o";this.e.MSG_SIGN_IN="Iniciar sesi\u00f3n";this.e.MSG_SIGN_OUT="Salir";this.e.MSG_PREVIOUS="\u00ab Anterior";this.e.MSG_NEXT="Siguiente \u00bb";this.e.MSG_NEWER="\u00ab M\u00e1s recientes";this.e.MSG_OLDER="Anteriores \u00bb";this.e.MSG_ACCEPT_ALL_FRIEND_REQUESTS="Aceptar todas";this.e.MSG_HELP_FRIENDREQUEST="Coincidir\u00e1s con tus amigos en todos los sitios de Google Friend Connect.";
this.e.MSG_HELP_FRIENDINVITE="Una vez que se\u00e1is amigos, coincidir\u00e9is en todos los sitios de Google Friend Connect.";this.e.MSG_HELP_BLOCKMEMBER="Si bloqueas a un usuario, lo eliminar\u00e1s de la lista de miembros e impedir\u00e1s que interact\u00fae con los dem\u00e1s usuarios de tu sitio.";this.e.MSG_INVITATION="Invitaci\u00f3n:";this.e.MSG_SEND="Enviar";this.e.MSG_BLOCK="Bloquear";this.e.MSG_IGNORE="Ignorar";this.e.MSG_CANCEL="Cancelar";this.e.MSG_SITE_SETTINGS="Configuraci\u00f3n del sitio";
this.e.MSG_ABOUT_FC="Acerca de Google Friend Connect";this.e.MSG_ALREADY_MEMBER="\u00bfYa eres miembro?";this.e.MSG_EDIT_PROFILE="Editar perfil"};gfc_7[gfc_].na={};
gfc_7[gfc_].lr=function(){this.na.MSG_SITE_MEMBERS="Seguidores";this.na.MSG_NO_SITE_MEMBERS="Todav\u00eda no hay seguidores.";this.na.MSG_SHOW_BLOCKED="Mostrar seguidores bloqueados \u00bb";this.na.MSG_SHOW_ALL="\u00ab Mostrar a todos los seguidores";this.na.MSG_ALL_SITE_MEMBERS="Todos los seguidores";this.na.MSG_ALL_BLOCKED_MEMBERS="Todos los seguidores bloqueados";this.na.MSG_NO_BLOCKED_MEMBERS="No has bloqueado a ning\u00fan seguidor.";this.na.MSG_LIKE_THIS_SITE="\u00bfTe gusta este blog?";this.na.MSG_JOIN=
"Seguir";this.na.MSG_BACK_TO_TOP="Miembros";this.na.MSG_JFJ="Seguir y conectarte con tus amigos";this.na.MSG_HELP_FRIENDREQUEST="Coincidir\u00e1s con tus amigos en los sitios de seguimiento de blogs y de Google Friend Connect.";this.na.MSG_HELP_FRIENDINVITE="Una vez que se\u00e1is amigos, coincidir\u00e9is en los sitios de Seguimiento de blogs y de Google Friend Connect."};
gfc_7[gfc_].K=function(a,b){var c=!0;if(b[gfc_o]&&b[gfc_o].person){var d={},e=b[gfc_o].person[gfc__b]()+" es tu amigo/a.";d.MSG_IS_FRIEND=e;e="Has invitado a "+(b[gfc_o].person[gfc__b]()+" a que sea tu amigo/a.");d.MSG_IS_INVITED=e;e="Amigos de "+b[gfc_o].person[gfc__b]();d.MSG_PROFILE_FRIENDS=e;e="Todos los amigos de "+b[gfc_o].person[gfc__b]();d.MSG_ALL_PROFILE_FRIENDS=e;for(var f in d)this.g(a,f,d[f])}b.invitedBy&&b.invitedBy[gfc__b]()&&(d=gfc_c[gfc_i]?gfc_c[gfc_i]:gfc_c[gfc_C][gfc_Zc]+2,c=(d-
135)/8,d=(d-175)/8,c="Ver el perfil de "+gfc_jn(b.invitedBy[gfc__b](),c),d=gfc_jn(b.invitedBy[gfc__b](),d)+" te ha invitado a este sitio.",this.g(a,"MSG_VIEW_INVITER_PROFILE",c),this.g(a,"MSG_INVITED_YOU",d),this.Tv=!0,c=!1);d="Hay "+(this.numWaitingMessages+" mensajes esper\u00e1ndote.");this.isMessagingEnabled&&0<this.numWaitingMessages&&(c=!1,this.g(a,"showWaitingMessages",!0),this.isMessagingEnabled&&(this.g(a,"MSG_NUM_WAITING_MESSAGES",d),this.g(a,"MSG_VIEW_AND_CONFIGURE_MESSAGING","Ver mensajes")));
b.friendRequests&&(0<b.friendRequests[gfc_Nb]()&&(c=!1),d=1==b.friendRequests[gfc_Nb]()?"Nueva solicitud de amistad \u00bb":"Nuevas solicitudes de amistad ("+(b.friendRequests[gfc_Nb]()+") \u00bb"),this.g(a,"MSG_NEW_FRIEND_REQUESTS",d));if(this.lb){if(this.bl(this.lb.themeId))for(f in this.na)this.g(a,f,this.na[f]);this.lb.signInPrompt&&this.g(a,"MSG_JOIN",this.lb.signInPrompt);this.lb.signOutPrompt&&this.g(a,"MSG_SIGN_OUT",this.lb.signOutPrompt)}this.g(a,"isViewerAdmin",b.isViewerAdmin);this.g(a,
"isMessagingEnabled",this.isMessagingEnabled);this.g(a,"acceptMessages",this.Nn);this.g(a,"isViewingSelf",b.viewer&&b[gfc_o]&&b[gfc_o].person&&b.viewer[gfc_E]()==b[gfc_o].person[gfc_E]());d=!1;if(b.owner&&(e=b.owner[gfc_I]("profileExtensions")))for(f in e)d=!0;this.g(a,"communityHasProfile",d);this.g(a,"promoHtml",c?this.promoHtml:null);this.g(a,"insertHtml",function(a,b){gfc_Ja(a,b)})};gfc_7[gfc_].bl=function(a){return"blogger"==a};
gfc_7[gfc_].Rg=function(a,b,c,d){gfc_Sn({id:a,text:b,version:this.bl(this.lb.themeId)?1:null,style:c},d)};
gfc_7[gfc_].O=function(a){function b(b,c){d.g(a,b,gfc_K(c,d))}this.g(a,"facesPerRow",this.Rb);for(var c in this.e)this.g(a,c,this.e[c]);var d=this;b("getThumbnail",this.tc);b("map",this.map);b("elide",gfc_jn);b("safeSlice",this.ni);b("showAllActivities",this.Ev);b("transformActivity",this.bc);b("nextActivities",this.ps);b("previousActivities",this.Xs);b("showAllLinks",this.Gv);b("transformLink",this.qw);b("nextLinks",this.ts);b("previousLinks",this.Zs);b("showAllSites",this.Jv);b("transformSite",
this.rw);b("nextSites",this.As);b("previousSites",this.ft);b("showAllMembers",this.Hv);b("showBlockedMembers",this.Lv);b("showUnblockedMembers",this.bw);b("nextMembers",this.us);b("nextBlockedMembers",this.qs);b("previousMembers",this.$s);b("previousBlockedMembers",this.Ys);b("showAllProfileFriends",this.Iv);b("nextProfileFriends",this.zs);b("previousProfileFriends",this.et);b("showAllViewerFriends",this.Kv);b("nextViewerFriends",this.Bs);b("previousViewerFriends",this.gt);b("isHome",this.Eh);b("goBack",
this.hh);b("goBackToHome",this.Vv);b("editSettings",this.Bb);b("signout",this.signout);b("signin",this.signin);b("viewProfile",this.Dn);b("blockUser",this.fj);b("unblockUser",this.uw);b("goToInviteFriend",this.sq);b("sendMessageDialog",this.cv);b("goToBlockMember",this.rq);b("goToEditProfile",this.Bb);b("goToViewerProfile",this.tq);b("sendInvite",this.bv);b("blockMember",this.fo);b("acceptFriendRequest",this.Mn);b("ignoreFriendRequest",this.ir);b("viewFriendRequests",this.Cw);b("acceptAllFriendRequests",
this.Ln);b("numPreviewFriends",this.Zp);b("numPreviewMembers",this.$p);b("showInvitedBy",this.fq)};
gfc_7[gfc_].uk=function(a){a=gfc_d.max(1,a?this.mc-1:this.mc);var b=this.d[gfc_k].members?this.d[gfc_k].members[gfc_Nb]():0,c=this.d[gfc_k].friends?this.d[gfc_k].friends[gfc_Nb]():0,b=gfc_d[gfc_wo](b/this.Rb),c=gfc_d[gfc_wo](c/this.Rb);b>gfc_d[gfc_wo](a/2)?c>gfc_d[gfc_4a](a/2)?(b=gfc_d[gfc_wo](a/2),c=gfc_d[gfc_4a](a/2)):b=gfc_d.max(0,a-c):c>gfc_d[gfc_4a](a/2)&&(c=gfc_d.max(0,a-b));b*=this.Rb;c*=this.Rb;return a={numMembers:b,numFriends:c}};gfc_7[gfc_].$p=function(a){return this.uk(a).numMembers};
gfc_7[gfc_].Zp=function(a){return this.uk(a).numFriends};gfc_7[gfc_].su=function(a,b){var c=gfc_e[gfc_H](),d={},e=gfc_e[gfc_D][gfc_Nc];d[e.FILTER]="PUBLICLY_VISIBLE";d[e.FIRST]=b[gfc_t];d[e.MAX]=b.pageSize?b.pageSize:this.la;var f=[gfc_e[gfc_x][gfc_q].ID,gfc_e[gfc_x][gfc_q][gfc__a],gfc_e[gfc_x][gfc_q][gfc_Db]];d[e[gfc_dc]]=f;d[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_0c];c.add(c[gfc_4b](gfc_qe(),d),"ownerFriends");c[gfc_n](a)};
gfc_7[gfc_].pt=function(a){this.d[gfc_k].members=a.get("ownerFriends")[gfc_l]()};gfc_7[gfc_].mu=function(a,b){var c=gfc_e[gfc_H](),d={},e=gfc_e[gfc_D][gfc_Nc];d[e.FIRST]=b[gfc_t];d[e.MAX]=b.pageSize?b.pageSize:this.la;d[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_0c];e={};e[gfc_e[gfc_Jb][gfc_q][gfc_Zb]]=gfc_e[gfc_Jb].PersonId.OWNER;e[gfc_e[gfc_Jb][gfc_q][gfc_Tb]]="BLOCKED";e[gfc_e[gfc_Jb][gfc_q][gfc_rc]]=1;e=gfc_e[gfc_nc](e);c.add(c[gfc_4b](e,d),"blockedMembers");c[gfc_n](a)};
gfc_7[gfc_].lt=function(a){this.d[gfc_k].blockedMembers=a.get("blockedMembers")[gfc_l]()};gfc_7[gfc_].yu=function(a,b){var c=gfc_e[gfc_H](),d=b&&b.person&&b.person[gfc_E]()||this.v[gfc_o].person[gfc_E](),e={},f=gfc_e[gfc_D][gfc_Nc];e[f.FIRST]=b[gfc_t];e[f.MAX]=b.pageSize?b.pageSize:this.la;d=this.Hl(d);e[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_0c];c.add(c[gfc_4b](d,e),"profileFriends");c[gfc_n](a)};
gfc_7[gfc_].Hl=function(a){var b={};b[gfc_e[gfc_Jb][gfc_q][gfc_Zb]]=a;b[gfc_e[gfc_Jb][gfc_q][gfc_Tb]]="FRIENDS";b[gfc_e[gfc_Jb][gfc_q][gfc_rc]]=1;return gfc_e[gfc_nc](b)};gfc_7[gfc_].ut=function(a){this.d[gfc_k][gfc_o].friends=a.get("profileFriends")[gfc_l]()};gfc_7[gfc_].Yi=function(a){for(var b=gfc_e[gfc_k].getDataContext(),c=0;c<a[gfc_B];c++){var d=a[c],d=b.getDataSet(d);if(!d||d.code)return!1}return!0};
gfc_7[gfc_].tu=function(a){var b=this.la,c=!b||24==b;c&&gfc_e[gfc_k]&&this.Yi(["ownerFriends","viewer","siteSettings","friendRequests"])?a(gfc_e[gfc_k].getDataContext()[gfc_l]()):(c=gfc_vo.newBatch(),b={userId:"@owner",groupId:"@friends",count:b,filterBy:"PUBLICLY_VISIBLE"},c.add("ownerFriends",gfc_vo.people.get(b)),c.add("viewer",gfc_vo.people.getViewer()),c.add("siteSettings",gfc_vo.extensions.get({command:"GetSiteSettings"})),c.add("friendRequests",gfc_vo.extensions.get({command:"GetFriendRequests",
params:'{"idSpec" : "VIEWER"}'})),(b=gfc_ca().psinvite)&&c.add("invitedBy",gfc_vo.extensions.get({command:"DecodeInvitation",params:{token:b}})),c.execute(a))};gfc_7[gfc_].qt=function(a,b){this.d[gfc_k].members=gfc_ie(a.ownerFriends,gfc_de);this.d[gfc_k].viewer=gfc_de(a.viewer);this.Zl(a,b,!0);this.lb=a[gfc_Oc];var c=gfc_ca();!c.psinvite||null!=this.d[gfc_k].viewer&&""!=this.d[gfc_k].viewer||(a.invitedBy&&(a.invitedBy.nickname=a.invitedBy.displayName),this.d[gfc_k].invitedBy=new gfc_e[gfc_x](a.invitedBy))};
gfc_7[gfc_].Lu=function(a,b){b=b||{};var c=b.pageSize||this.maxFacesPerPage,d=!b[gfc_t]||0==b[gfc_t],e=!c||20==c;d&&e&&gfc_e[gfc_k]&&this.Yi(["friends","isViewerAdmin"])?a(gfc_e[gfc_k].getDataContext()[gfc_l]()):(d=gfc_vo.newBatch(),c={userId:"@viewer",groupId:"@friends",count:c},b[gfc_t]&&(c.startIndex=b[gfc_t]),d.add("friends",gfc_vo.people.get(c)),d.add("isViewerAdmin",gfc_vo.people.get({userId:"@viewer",groupId:"ADMINS"})),d.execute(a))};
gfc_7[gfc_].At=function(a){var b=a.friends;b&&!b[gfc_pc]&&(this.d[gfc_k].friends=gfc_ie(b,gfc_de));this.Em(a)};gfc_7[gfc_].Mu=function(a){var b=gfc_e[gfc_H]();b.add(gfc_ge("VIEWER"),"numWaitingMessages");b[gfc_n](a)};gfc_7[gfc_].Ct=function(a){this.numWaitingMessages=a.get("numWaitingMessages")[gfc_l]().numberOfWaitingMessages};
gfc_7[gfc_].Au=function(a){this.log("requesting promo");var b=new gfc_a[gfc_Cc],b=b.getLang()+(b[gfc_fd]()?"_"+b[gfc_fd]():""),c=gfc_e[gfc_H]();c.add(gfc_6d("GetPromo",{hl:b}),"promo");c[gfc_n](a)};gfc_7[gfc_].wt=function(a){this.log("processing promo");(a=a.get("promo")[gfc_l]())&&-1!=a.promoCode&&(this.promoCode=a.promoCode,this.promoHtml=a.promoHtml)};
gfc_7[gfc_].Un=function(){for(var a=function(){this.promoHtml=null;for(var a=gfc_0f("div","fc-promo-main",gfc_P("peg")),b=0;b<a[gfc_B];b++)gfc_Jh(a[b],!1);this.Y();this.log("Dismissing promo "+this.promoCode);a=gfc_e[gfc_H]();a.add(gfc_6d("DismissPromo",{promoCode:this.promoCode}));a[gfc_n](gfc_K(function(){this.log("The promo has been dismissed");this.promoCode=-1},this))},b=gfc_0f("a","fc-promo-dismiss-link",gfc_P("peg")),c=0;c<b[gfc_B];c++){var d=b[c],e="click";gfc_Si(d,e);gfc_Ii(d,e,gfc_K(a,this))}};
gfc_7[gfc_].Em=function(a){var b=a.isViewerAdmin;b&&!b[gfc_pc]?this.d[gfc_k].isViewerAdmin=b.list[gfc_B]:a.get&&a.get("isViewerAdmin")&&(a=a.get("isViewerAdmin"))&&!a[gfc_Bc]()&&(this.d[gfc_k].isViewerAdmin=a[gfc_l]()[gfc_Nb]())};gfc_7[gfc_].Ln=function(a){var b=[];a.each(function(a){a={user:a[gfc_I](goog.opensocial.peoplesense.Invite[gfc_q].INVITER)[gfc_E](),action:"ACCEPT"};b[gfc_v](a)});this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_K(this.yg,this),{friendRequestResponses:b})};
gfc_7[gfc_].Vv=function(){this.ea();this.render(["members","viewerFriends"],"faces")};gfc_7[gfc_].Mn=function(a){a={user:a[gfc_E](),action:"ACCEPT"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_K(this.yg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].Cw=function(){this.ea();this.B("friend-requests")};gfc_7[gfc_].Dn=function(a){this.Hb()?(this.ea(),this.Ew(a)):gfc_3d(a[gfc_E]())};
gfc_7[gfc_].Ew=function(a){this.render(["profileData","profileFriends","activityData"],"profile",{person:a})};gfc_7[gfc_].Gu=function(a,b){var c=gfc_e[gfc_H](),d=gfc_e[gfc_D][gfc_Nc],e={};e[d.FIRST]=b&&b[gfc_t]?b[gfc_t]:0;var f=this.d[gfc_k][gfc_o].person[gfc_E]();e[d.MAX]=this.jn;c.add(gfc_ne(gfc_e[gfc_nc]({userId:f}),e),"profileSites");c[gfc_n](a)};gfc_7[gfc_].yt=function(a){this.d[gfc_k][gfc_o].sites=a.get("profileSites")[gfc_l]()};
gfc_7[gfc_].xu=function(a,b){this.d[gfc_k].profile={};b=b||{};var c=b.person,d={},c=c[gfc_E](),e=gfc_e[gfc_H](),f=[gfc_e[gfc_x][gfc_q].ID,gfc_e[gfc_x][gfc_q][gfc__a],gfc_e[gfc_x][gfc_q][gfc_Db],gfc_e[gfc_x][gfc_q].ABOUT_ME,gfc_e[gfc_x][gfc_q].URLS,"profileExtensions"],g=gfc_e[gfc_D][gfc_Nc];d[g[gfc_dc]]=f;d[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_0c];e.add(e.newFetchPersonRequest(c,d),"profile");e.add(e.newFetchPersonRequest("VIEWER",d),"viewer");e.add(gfc_le("VIEWER","ADMINS"),
"isViewerAdmin");e.add(e.newFetchPersonRequest("OWNER",d),"owner");this.lb||e.add(gfc_fe(),"siteSettings");e.add(gfc_le(c,"ADMINS"),"isAdmin");e.add(gfc_le(c,"BLOCKED"),"isBlocked");this.isMessagingEnabled&&e.add(gfc_ge(c),"canMessage");e[gfc_n](a)};
gfc_7[gfc_].Ff=function(a,b){var c=b.person[gfc_E](),d=gfc_e[gfc_nc]({userId:c}),e=gfc_e[gfc_H]();(this.d[gfc_k].viewer&&c!=this.d[gfc_k].viewer[gfc_E]()||this.Hb())&&e.add(gfc_ke(b.person[gfc_E](),"VIEWER"),"isProfileFriend");e.add(e[gfc_4c](d,{}),"activities");e[gfc_n](a)};
gfc_7[gfc_].gd=function(a,b){null!=a.get("activities")[gfc_l]()&&(this.d[gfc_k][gfc_o].activities=a.get("activities")[gfc_l]());var c=a.get("isProfileFriend");c&&b&&null!=this.d[gfc_k].viewer&&this.d[gfc_k].viewer[gfc_E]()!=b.person[gfc_E]()&&(this.d[gfc_k][gfc_o].isFriend=c[gfc_l]()[gfc_w])};
gfc_7[gfc_].tt=function(a,b){var c=a.get("profile")[gfc_l]();this.d[gfc_k][gfc_o].person=c;this.d[gfc_k][gfc_o].person.externalProfileUrl=null;var d=c[gfc_I](gfc_e[gfc_x][gfc_q].URLS),e=[];if(d)for(var f=0;f<d[gfc_B];f++){var g=d[f];"profile"!=g[gfc_I](gfc_e.Url[gfc_q].TYPE)&&"externalProfile"!=g[gfc_I](gfc_e.Url[gfc_q].TYPE)&&e[gfc_v](g);"externalProfile"==g[gfc_I](gfc_e.Url[gfc_q].TYPE)&&(this.d[gfc_k][gfc_o].person.externalProfileUrl=g[gfc_I](gfc_e.Url[gfc_q].ADDRESS))}this.d[gfc_k][gfc_o].links=
new gfc_zo(e,this.of,0);this.d[gfc_k].owner=a.get("owner")[gfc_l]();this.d[gfc_k].viewer=a.get("viewer")[gfc_l]();(d=this.d[gfc_k].viewer)&&b.person[gfc_E]()!=this.d[gfc_k].viewer[gfc_E]()&&(this.d[gfc_k][gfc_o].isAdmin=a.get("isAdmin")[gfc_l](),this.d[gfc_k][gfc_o].isAdmin&&(this.d[gfc_k][gfc_o].isAdmin=this.d[gfc_k][gfc_o].isAdmin[gfc_Nb]()),this.d[gfc_k][gfc_o].isBlocked=a.get("isBlocked")[gfc_l](),this.d[gfc_k][gfc_o].isBlocked&&(this.d[gfc_k][gfc_o].isBlocked=this.d[gfc_k][gfc_o].isBlocked[gfc_Nb]()));
c=c[gfc_I]("profileExtensions");c=this.Lb.ef(c,this.Lb.xi);d=[];for(f in c){e=c[f];g={};g.title=e.title;var h=!1;if("SHORT_TEXT"==e[gfc_Xc]||"LONG_TEXT"==e[gfc_Xc])e[gfc_w]&&e[gfc_w][gfc_wc]&&(g.body=[],g[gfc_C][gfc_v](e[gfc_w][gfc_wc]),h=!0);else if(e[gfc_w]&&e[gfc_w].choice&&0<e[gfc_w].choice[gfc_B]){g.body=[];for(h=0;h<e[gfc_w].choice[gfc_B];++h)g[gfc_C][gfc_v](e[gfc_w].choice[h][gfc_hc]);h=!0}h&&d[gfc_v](g)}this.d[gfc_k][gfc_o].profileExtensions=d;this.lb||(this.lb=a.get("siteSettings")[gfc_l]());
this.isMessagingEnabled&&(f=(f=a.get("canMessage"))&&f[gfc_l]().canSendMessage,this.d[gfc_k][gfc_o].canSendMessage=f);this.Em(a)};gfc_7[gfc_].fj=function(a){this.render(["blockUser"],"profile",{person:a})};gfc_7[gfc_].uw=function(a){this.render(["unblockUser"],"profile",{person:a})};gfc_7[gfc_].map=function(a,b){var c=[],d=gfc_K(function(a,b,c){a[gfc_v](b(c))},this,c,b);a.each(d);return c};gfc_7[gfc_].Hv=function(){this.ea();this.B("members-page")};
gfc_7[gfc_].Lv=function(){this.ea();this.render(["blocked-member-page"],"blocked-members-page",{start:0})};gfc_7[gfc_].bw=function(){this.Gi()};gfc_7[gfc_].us=function(a){this.render(["member-page"],"members-page",{start:this.la+a.getOffset()})};gfc_7[gfc_].$s=function(a){this.render(["member-page"],"members-page",{start:a.getOffset()-this.la})};gfc_7[gfc_].qs=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:this.la+a.getOffset()})};
gfc_7[gfc_].Ys=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:a.getOffset()-this.la})};gfc_7[gfc_].Kv=function(){this.ea();this.B("viewer-friends-page")};gfc_7[gfc_].Bs=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:this.la+a.getOffset()})};gfc_7[gfc_].gt=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:a.getOffset()-this.la})};gfc_7[gfc_].Iv=function(){this.ea();this.B("profile-friends-page")};
gfc_7[gfc_].zs=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:this.la+a.getOffset(),person:this.d[gfc_k][gfc_o].person})};gfc_7[gfc_].et=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:a.getOffset()-this.la,person:this.d[gfc_k][gfc_o].person})};gfc_7[gfc_].Gv=function(){this.ea();this.B("links")};gfc_7[gfc_].ts=function(a){var b=this.of+a.getOffset();this.d[gfc_k][gfc_o].links=new gfc_zo(a.all(),this.of,b);this.B("links")};
gfc_7[gfc_].Zs=function(a){var b=a.getOffset()-this.of;this.d[gfc_k][gfc_o].links=new gfc_zo(a.all(),this.of,b);this.B("links")};gfc_7[gfc_].Jv=function(){this.ea();this.B("sites")};gfc_7[gfc_].As=function(a){this.render(["sitesData"],"sites",{start:this.jn+a.getOffset()})};gfc_7[gfc_].ft=function(a){this.render(["sitesData"],"sites",{start:a.getOffset()-this.jn})};gfc_7[gfc_].Ev=function(){this.ea();this.B("activities")};
gfc_7[gfc_].ps=function(a){this.render(["activityData"],"activities",{start:this.Ba+a.getOffset()})};gfc_7[gfc_].Xs=function(a){this.render(["activityData"],"activities",{start:a.getOffset()-this.Ba})};gfc_7[gfc_].Ve=function(a){this.render(["deleteActivity"],this.d[gfc_9c],{activity:a})};gfc_7[gfc_].lu=function(a,b){var c=gfc_e[gfc_H]();c.add(gfc_me(b.person[gfc_E](),["BLOCKED"],[]),"block");this.ad();c[gfc_n](a)};
gfc_7[gfc_].kt=function(a){if(a=!a.get("block")[gfc_Bc]())this.d[gfc_k][gfc_o].isBlocked=!0};gfc_7[gfc_].Ju=function(a,b){var c=gfc_e[gfc_H]();c.add(gfc_me(b.person[gfc_E](),[],["BLOCKED"]),"unblock");this.ad();c[gfc_n](a)};gfc_7[gfc_].zt=function(a){if(a=!a.get("unblock")[gfc_Bc]())this.d[gfc_k][gfc_o].isBlocked=!1};
gfc_7[gfc_].Gf=function(a,b){var c=b.activity,d=c[gfc_I](gfc_e[gfc_6b][gfc_q].ID),c=gfc_e[gfc_nc]({userId:c[gfc_I](gfc_e[gfc_6b][gfc_q][gfc_Zb])}),e=gfc_e[gfc_H]();e.add(gfc_7d(d),"delete");e.add(e[gfc_4c](c,{}),"activities");e[gfc_n](a)};
gfc_7[gfc_].bc=function(a){var b=gfc_0n,c=function(a){return a=a[gfc_j](/<a/g,"<a target='_top'")},d=null,e=this.d[gfc_k].viewer;null!=e&&a[gfc_I](gfc_e[gfc_6b][gfc_q][gfc_Zb])==this.d[gfc_k].viewer[gfc_E]()&&(d=gfc_K(this.Ve,this,a));(e=a[gfc_I](gfc_e[gfc_6b][gfc_q].STREAM_FAVICON_URL,{escapeType:"none"}))||(e=gfc_b.friendconnect_imageUrl+"/favicons.gif");return{icon:e,time:b(gfc_ga(a[gfc_I](gfc_e[gfc_6b][gfc_q].POSTED_TIME))),link:a[gfc_I](gfc_e[gfc_6b][gfc_q].STREAM_URL,{escapeType:"none"}),siteTitle:a[gfc_I](gfc_e[gfc_6b][gfc_q].STREAM_TITLE,
{escapeType:"none"}),innerHTML:c(a[gfc_I](gfc_e[gfc_6b][gfc_q].TITLE,{escapeType:"none"})),body:c(a[gfc_I](gfc_e[gfc_6b][gfc_q].BODY,{escapeType:"none"})),deleteHandler:d}};gfc_7[gfc_].rw=function(a){var b=gfc_a[gfc_ac].unescapeString,c=gfc_xo;return{icon:c(a[gfc_I](gfc_e[gfc_x][gfc_q][gfc_Kc])),link:a[gfc_I](gfc_e[gfc_x][gfc_q][gfc_Kc]),title:b(a[gfc__b]())}};
gfc_7[gfc_].qw=function(a){var b=gfc_a[gfc_ac].unescapeString,c=gfc_xo,d=a[gfc_I](gfc_e.Url[gfc_q].ADDRESS);return{icon:c(d),link:d,title:b(a[gfc_I](gfc_e.Url[gfc_q].LINK_TEXT))||d}};gfc_7[gfc_].zu=function(a,b){var c=gfc_e[gfc_H](),d=b.person[gfc_E](),e=gfc_e[gfc_D][gfc_Nc],f=this.Hl(d),g={};g[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_0c];c.add(c[gfc_4b](f,g),"friends");f={};f[e.FIRST]=this.Mx;f[e.MAX]=this.Lx;c.add(gfc_ne(gfc_e[gfc_nc]({userId:d}),f),"profileSites");c[gfc_n](a)};
gfc_7[gfc_].ir=function(a){a={user:a[gfc_E](),action:"DENY"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_K(this.yg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].yg=function(a){return a&&a["next-view"]?a["next-view"]:["friend-requests"]};gfc_7[gfc_].Fu=function(a,b){var c=b[gfc_o],d=gfc_e[gfc_H]();d.add(gfc_8d(c[gfc_E](),b.message),"friendRequest");this.ad();d[gfc_n](a)};gfc_7[gfc_].xt=function(a){a.get("friendRequest")[gfc_Bc]()||(this.d[gfc_k][gfc_o].isInvited=!0)};
gfc_7[gfc_].pu=function(a,b){var c=gfc_vo.newBatch(),d=b.friendRequestResponses;c.add("updateFriendRequest",gfc_vo.extensions.get({command:"ProcessFriendRequests",params:'{"requests":'+gfc_a[gfc_8b].stringify(d)+"}"}));c.add("friendRequests",gfc_vo.extensions.get({command:"GetFriendRequests",params:'{"idSpec" : "VIEWER"}'}));this.ad();c.execute(a)};gfc_7[gfc_].sq=function(){this.ea();this.B("invite-friend")};gfc_7[gfc_].cv=function(a){this.isMessagingEnabled&&(a=a[gfc_I](gfc_e[gfc_x][gfc_q].ID),this.dv(a))};
gfc_7[gfc_].dv=function(a){if(this.isMessagingEnabled){a="/friendconnect/messaging/compose?recipientId="+a;var b=570,c=395;gfc_Kn(a,gfc_g(b),gfc_g(c))}};gfc_1[gfc_].Nn=function(){var a="/friendconnect/messaging/accept",b=570,c=375;gfc_Kn(a,gfc_g(b),gfc_g(c));return!1};gfc_7[gfc_].rq=function(){this.ea();this.B("block-member")};gfc_7[gfc_].tq=function(){this.Dn(this.d[gfc_k].viewer)};
gfc_7[gfc_].bv=function(a){this.vf();a={profile:a};var b=gfc_P("inviteMessage");b&&(a.message=gfc_4g(b));this.render(["sendFriendRequest"],"profile",a)};gfc_7[gfc_].fo=function(a){this.vf();this.fj(a)};gfc_7[gfc_].Zl=function(a,b,c){c=c||!1;this.d[gfc_k].friendRequests=gfc_ie(a.friendRequests,gfc_$d);0<this.d[gfc_k].friendRequests[gfc_Nb]()?b["next-view"]="friend-requests":b["next-view"]="faces";c||gfc_vn("friend")};
gfc_7[gfc_].vt=function(a){this.d[gfc_k][gfc_o].sites=a.get("profileSites")[gfc_l]();this.d[gfc_k][gfc_o].friends=a.get("friends")[gfc_l]()};gfc_7[gfc_].fq=function(){return this.Tv};gfc_7[gfc_].Y=function(){this.ix.rebuild();this.Un();gfc_a[gfc_Wc].adjustHeight()};gfc_7[gfc_].Os=function(a){return a=gfc_Q("span",{"class":"fc-cap-link-big"},gfc_Q("a",{"class":"fc-cap-link-big"},this.e.MSG_OPTIONS),a.Cg())};
gfc_7[gfc_].Ns=function(){var a=[];a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-settings"},this.e.MSG_SITE_SETTINGS);this.isSocialShareEnabled&&(a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-share"},this.e.MSG_MEMBERS_SHARE));this.d[gfc_k].isViewerAdmin&&!this.Hb()&&(a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-manage"},this.e.MSG_MANAGE));a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-signout"},this.lb.signOutPrompt||this.e.MSG_SIGN_OUT);a[a[gfc_B]]=
gfc_Q("div",{"class":"goog-menuseparator fc-menuseparator-line"});a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-aboutfc"},gfc_Q("span",{"class":"fc-small-menu-link"},this.e.MSG_ABOUT_FC));return a};
gfc_7[gfc_].Ps=function(a){a[gfc_Wb]();a=a[gfc_F].h()[gfc_Yc];a[gfc_fb]("menuaction-settings")?this.Bb():a[gfc_fb]("menuaction-share")?this.share():a[gfc_fb]("menuaction-signout")?this.signout():a[gfc_fb]("menuaction-manage")?this.xq():a[gfc_fb]("menuaction-aboutfc")&&(a=gfc_b[gfc_tc](gfc_Cn()+"/friendconnect/home/overview"),a[gfc_lb]())};gfc_7[gfc_].xq=function(){var a={},b=gfc_a[gfc_r][gfc_5a]()[gfc_jc];gfc_vn("lightbox");gfc_a[gfc_r].requestNavigateTo(b,a);return!1};
var gfc_yo=function(a){for(var b={},c=0;c<a[gfc_B];++c)b[a[c]]=a[c];return b}("HEIGHT BORDER_COLOR CONTENT_BG_COLOR CONTENT_HEADLINE_COLOR CONTENT_LINK_COLOR CONTENT_SECONDARY_TEXT_COLOR CONTENT_SECONDARY_LINK_COLOR CONTENT_TEXT_COLOR ENDCAP_BG_COLOR ENDCAP_LINK_COLOR ENDCAP_TEXT_COLOR FACE_SIZE NUMBER_ROWS".split(" "));
gfc_7[gfc_].s=function(){var a=gfc_yo,b=[],c=0;this.f(a.HEIGHT);this.Hh()&&(b[c++]=this.j(".fc-thumbnail img {height:%spx;width:%spx}",this.f(a.FACE_SIZE)));b[c++]=this.j(".fc-scroll-botnav, .fc-scroll, .fc-noscroll-botnav {height: %spx;}\n",this.zm);b[c++]=this.j(".fc-members,.fc-members-canvas {border-color: %s;}\n.fc-userpage-itemlist,.fc-userpage-itemlist-canvas,.fc-botcap-short { border-top-color: %s; }\n.fc-topcap,.fc-topverb,.fc-friendreq,.fc-friendreqs,.fc-timeframe { border-bottom-color: %s; }\n",
this.f(a.BORDER_COLOR));this.cf()&&(this.Pk("profile")?b[c++]=".fc-topcap {height: "+this.slimTopCapHeight+"px;}\n":this.Kh()?b[c++]=".fc-topcap {height: 0px;}\n":b[c++]=".fc-topcap {height: "+this.tinyTopCapHeight+"px;}\n");this.Hb()?b[c++]=".fc-userpic-caption {margin-left: 59px;}\n":b[c++]=".fc-userpic-caption {margin-left: 40px;}\n";this.Kh()?b[c++]=".fc-topcap-color {background-color: white;}\n":b[c++]=this.j(".fc-topcap-color {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));this.cl()?b[c++]=
".fc-botcap-short {background-color: white;}\n":b[c++]=this.j(".fc-botcap-short {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-topcap, .fc-botverb, .fc-topverb, .fc-botcap-short, .fc-header-sectitle, .fc-members-header {color: %s;}\n",this.f(a.ENDCAP_TEXT_COLOR));
b[c++]=this.j(".fc-botverb,.fc-topcap .fc-menutriangle-down, .fc-topcap .fc-menutriangle-up,.fc-topcap a, .fc-topcap a:active, .fc-topcap a:visited,.fc-topcap-link a, .fc-topcap-link a:active, .fc-topcap-link a:visited,.fc-cap-link-big a, .fc-cap-link-big a:active,.fc-left-verb a, .fc-left-verb a:active, .fc-left-verb a:visited,.fc-right-verb a, .fc-right-verb a:active, .fc-right-verb a:visited,.fc-subtle-botcap a, .fc-subtle-botcap a:active, .fc-subtle-botcap a:visited.fc-left-verb-canvas a, .fc-left-verb-canvas a:active, .fc-left-verb-canvas a:visited,.fc-right-verb-canvas a, .fc-right-verb-canvas a:active, .fc-right-verb-canvas a:visited {color: %s;}\n",
this.f(a.ENDCAP_LINK_COLOR));b[c++]=this.j(".fc-content-bg, .fc-subtle-botcap {background-color:%s;}\n",this.f(a.CONTENT_BG_COLOR));b[c++]=this.j(".fc-content a, .fc-content a:active, .fc-content a:visited,\n.fc-item-body a, .fc-item-body a:active, .fc-item-body a:visited,\n.fc-see-all a, .fc-see-all a:active, .fc-see-all a:visited,\n.fc-content-link a, .fc-content-link a:active, .fc-content-link a:visited,\n.fc-content-canvas a, .fc-content-canvas a:active, .fc-content-canvas a:visited {color: %s;}\n",
this.f(a.CONTENT_LINK_COLOR));b[c++]=this.j(".fc-members,.fc-members-canvas {color:%s;}\n",this.f(a.CONTENT_TEXT_COLOR));b[c++]=this.j(".fc-helpful,.fc-on-other-site,.fc-no-elements, .ot-activity-metadata {color:%s;}\n",this.f(a.CONTENT_SECONDARY_TEXT_COLOR));b[c++]=this.j(".fc-faded-link a, .fc-faded-link a:active, .fc-faded-link a:visited, .fc-faded-link-small a, .fc-faded-link-small a:active, .fc-faded-link-small a:visited {color: %s;}\n",this.f(a.CONTENT_SECONDARY_LINK_COLOR));b[c++]=this.j(".fc-sectitle {color: %s;}\n",
this.f(a.CONTENT_HEADLINE_COLOR));return gfc_7.i.s[gfc_G](this)+b[gfc_J]("\n")};gfc_L("goog.peoplesense.gadget.Members",gfc_7);gfc_L("goog.peoplesense.gadget.Members.start",gfc_7[gfc_t]);var gfc_zo=function(a,b,c){gfc_e.Collection[gfc_G](this,a[gfc_yc](c,c+b),c,a[gfc_B]);this.Nw=a;this.da=b};gfc_zo.inherits(gfc_e.Collection);gfc_zo[gfc_].all=function(){return this.Nw};gfc_zo[gfc_].qb=function(){return this.da};gfc_L("goog.peoplesense.gadget.Members.PagedCollection.prototype.all",gfc_zo[gfc_].all);
gfc_L("goog.peoplesense.gadget.Members.PagedCollection.prototype.getPageSize",gfc_zo[gfc_].qb);
